# Generated by Django 4.2.19 on 2025-02-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_access_token',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_refresh_token',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_token_expires_at',
        ),
    ]
