# Generated by Django 4.2.19 on 2025-02-27 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steamroomandselfcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
